#!/bin/bash

source $(dirname "${0}")/_local-hook-exec

# for lint-staged
export FORCE_COLOR=1

# for global-hook ignore option
if [[ -n $NO_VERIFY_GLOBAL ]]; then
  exit 0
fi

declare scriptDir=$(cd $(dirname $0) || exit;pwd)
declare parentDir="$(dirname "${scriptDir}")"

"${parentDir}/node_modules/.bin/lint-staged" --config ${parentDir}/lint-staged.config.js
